

= Future Of Competition (Notes)
:bibliography-database: foc_bibliography.bib
:bibliography-style: apa

*Format* options include 10-page policy paper, blog post, everything
in between.  1000 to 1500 words on up.

We need to balance the idealistic explanation of history and framing
with the practical reality of political limitations and current
structures.  Maybe those are two parts of the same doc, but they need
to be somewhat clearly separated.

== Potential Sections
=== We're framing this wrong
 * Competition is about power of participants
 * when power hits coercive levels, we have problems
 * Coercion is a spectrum and some coercion might be ok
 * Omnipresence can create this coercion, not just monopoly
 * One antidote to this is options (or competition or agency)
 * Options != competition necessarily
 * Policy framed around monopoly isn't useful-- use can have coercion without monopoly, and the solutions aren't centered on competition.  We're also not worried about consumer pricing
 * Common carrier is another frame people reach for but there's no good reason for it here.
 * The availability of options is important even if you never take them (think forking open source code, or building new apps and services)
 * The traditional language, framing, and legal concepts around antitrust don't fit this. There are practical reasons to need to squeeze the internet circle into these squares to use existing law in litigation; but for new regulatory approaches, we can and should recognize the nature of this and approach it more effectively.
 * Maybe we can ask some EU folks for the framing over there so we can either take good ideas or cite them as more examples of poor framing
 * If competition is the wrong frame, maybe "Future Of Competition" is the wrong title
 * We need more work here to develop the *right* frame
 * Feld also critiques the "resort to antitrust", and he (as is typical) tosses in a some history on regulation for the public good as opposed to for market management. cite:[feld:01, locator="Introduction, Section A"]
 * interoperability is gaining traction, along with structural separation
 * one idea: we're framing this wrong - the harm we're tracking isn't antitrust harm per se, or consumer harm, it's user harm - the point is not "hey stop framing it this way" but rather "recognize that where we're coming from shapes our current state" - we can and must work with the structures that we have, but it's critical to acknowledge the flaws in the metaphor
 * recognize the limits of our framing, and the thing that we craft now has to bridge the gap in our conceptual reality
 * need to allude to places where the framing leads us astray but without going too far down the rabbit holes
 * grounded in US law/policy and regulatory philosophy but this is a broader conversation particularly in EU+UK
 * we're looking to a future where different regions experiment with applying different regulatory+enforcement paradigms to this still-new space - UK w OFCOM implementing the duty of care, EU with multi-state mechanisms (like DPAs) - lots of things will break over the next few years, and that's OK as long as we learn from it and iterate with our governance in the same way we iterate with our technology
 * infrastructure works best when it's open. search, social, etc are now infra in a way they haven't been before. we expect more openness now than we did, and we should expect that because it's the optimal approach. just because the infra is vertically integrated with the UX doesn't mean it isn't infra.
 * If you're going to break anything up, the answer isn't to force Google to dump YouTube, it's separating the platform infra from the UI, which can effectively be done via interop. Same for Facebook - you don't carve out Instagram, you separate the network infra core from the UI. Google search does have at least some interop in this sense.  See https://startpage.com/.  Google apparently shares the index, but not the click data that helps them score it.  Where do we draw the line between the platform and the UI.  Is the click trail part of the platform?  We would say definitely. Why though and what are the repeatable principles that help extend it?

 * The Web's Missing Interoperability is close but not right: "To that
   end, to the extent regulators want to engender competition... the
   solution is clear: force existing social networks to open up their
   social graphs." cite:[stratechery:01] Competition isn't the goal.
   Interop puts power in the hands of users.  It's not about making
   more/better/cheaper service providers.  It's about making users
   somewhat agnostic to service provider choice.

=== Counterpoint: we're framing this right
 * There are some aspects of regulating big tech that *are* rightly about competition
 * exclusivity agreements, acquisition of threats, non-compete, no-poaching agreements, etc.
 * We need to acknowledge that talk about the dividing line
 * We need to deal with this complexity in the regulatory approach to some degree
 
=== Counter-counter-point: competition framing is half-wrong, half-right
 * EU's Digital Markets Act was designed as a complement to antitrust regulation, and identifies a set of obligations for "gatekeepers." cite:[voxeu:01] These obligations are principally technical in nature, rather than economic.
 * The economic aspects of the conversation, including exclusivity agreements, non-compete, merger review standards, presumptions etc. - those are all part of the domain of antitrust, and areas where the unique characteristics of the internet as a market or set of markets do not fundamentally distinguish it from other markets, with the exception of our limited toolkit for effectively measuring the value of data and evaluating consumer welfare in a field dominated by zero user facing prices.
 * But the DMA really opens up the conversation around technical gatekeeping, practices that are structurally distinguishable from classic antitrust because they more closely resemble a statutory translation of common carrier principles into the internet ecosystem. They reflect a governance decision to introduce proactive measures designed to enrich a broader ecosystem and innovation at the edge, recognizing the costs and changed incentives they impose on platform services.
 * Rather than directly use the phrase "common carrier", "essential facility", or other concepts from prior contexts, let's use a new term to characterize these obligations so we can start our analysis from a fresh mindset - how about *open gatekeepers*?

=== Gatekeeper misbehavior, in the eyes of the DMA:
==== Article 5, self-executing:
 * Combining personal data with 3rd party services
 * Signing end users into other services to make them 1st party as a way to circumvent the above (i.e. using FB auth to login to a website doesn’t make it 1st party)
 * Prohibiting business users from offering products/services on different terms on other platforms
 * Mandatory arbitration agreements for business users (i.e. can’t complain to gov)
 * Requiring “business users” to work with platform’s own identification service (i.e. for a seller to buy ads on FB/Google they have to let their users auth w FB/Google); this is also related to combining data across services
 * Required services bundling (intended primarily to cover ad tech stack bundling)
 * Hiding prices for advertising/publishing (i.e. statutory requirement to disclose specific pricing info related to specific ads) (unclear what specific harm this is?)
 
==== Article 6, “susceptible of being further specified” i.e. maybe negotiated: 
 * Using non-public data associated with business users to compete with them (Amazon rolling out white label copies problem; could also cover G ad practices)
 * Blocking user removal of pre-installed software except where it is necessary for the functioning of the device and can’t technically be offered standalone (i.e. let them uninstall web browsers or Google apps on a Google phone, but also Apple)
 * Blocking 3rd party apps, app stores, and sideloading (however you can install security measures to keep them from harming the device/operating system)
 * Self-preferencing in “ranking services and products” (search, stores) (rule requires “fair and non-discriminatory conditions” for ranking)
 * Blocking user switching (unclear what this means or how it’s different from installing non-dominant apps)
 * Not allowing “business users and providers of ancillary services” interoperability on the same terms as “ancillary services” offered by the gatekeeper
 * Not providing advertisers and publishers access to performance measuring tools / blocking independent verification of ad inventory
 * Not supporting effective data portability, “including continuous and real-time access”, scoped for “data generated through the activity of a business user or end user” (whatever that means)
 * Not providing business users or authorized third parties of business users with data relevant for interoperability (this is confusing, provision i)
 * Not providing click, query, and view data for search on FRAND terms
 * Not applying fair and non-discriminatory access to app stores
 
==== Clustering
 * Combining data and related provisions: Privacy intervention cognizable within the Open Gatekeepers bucket of policies, arguably
 * Prohibiting offerings on other terms: Feels more like antitrust
 * Mandatory arbitration: Antitrust (or consumer protection?)
 * Identification services provisions: Open Gatekeepers, I would argue; there's a case to call it antitrust bc tying, but identification is so fundamental a technical concept and so intersecting with combining data that it stands apart
 * Services bundling in general: Antitrust/tying, unless there's some higher standard that reaches to limitations on downstream innovation or privacy
 * Hiding prices for advertising/publishing: Open Gatekeepers - feels more akin to transparency obligations associated with common carrier practices
 * Everything in Article 6 falls in the Open Gatekeelers buckets - the EU recognizes that these are uncertain, subject to future negotiation, 

=== Stacks and edges
 * TCP/IP was the service until it became infra
 * Web was the service until it became infra
 * Maybe social isn't a service anymore, it's infra (and should be treated as such by law).  Or maybe the platform is infra and the interface is a service.
 * As things become infra, their coercive power naturally/inherently increases, which is why we need to start worrying about their openness (nobody cared that FB was ivy-only in 2003)
 * Options / agency come in at that point

=== Politics
 * Do we think about this from an FTC or an FCC perspective?  Some of this comes down to antitrust vs competition law.  Chris says this isn't an antitrust problem, but it *is* a competition problem.  James says it's neither.  The harm isn't consumer harm, it's user harm.  This feels like FCC, not FTC territory.
 * Or do we need a new perspective entirely?
 * There's a mismatch between the political reality and the technical conversations
 * If we're saying monopoly is the wrong frame, we're kinda saying we don't care about FTC.  You can have your monopoly if I get my open access
 * At the same time, this is different from common carrier / historical communications paradigms where monopolies are inherently efficient and regulated

=== What Should the Regulatory Approach Look Like?
 * The approach flows the framing we say is right in section 1
 * How do we mandate some amount of open access while preserving a service's ability to moderate?  The answer is probably some kind of non-discrimination rule.  That is, external access has to meet the same standards as traffic that originates locally.  And one exception: there should probably be a line beyond which you can cut entire groups of users (e.g. all of Parler) to protect your users, even if this is over-broad and blocks some content that isn't actually problematic by your usual moderation rules.

=== China
 * What kind of a say does China get?
 * To the extent they open up, they get a say.
 * It's a risk to policy that we don't have a good view on what's going to happen here.
 * How do we create incentives/tradeoffs that move the market toward our view of competition and interop, even when a giant economy drags its feet?
 * arguably we did that once - the open web showed that decentralization and open flow led to faster and better innovation than centralized control. but now we have to prove that again, somehow?
 * centralization empowers gatekeeping which ensures good value capture
 * we don't know what would happen if we invested comparable resources (billions$) in decentralization - in some past systems at smaller scale, the lack of capture starved future resources/stabilization.
 * backwards compatibility is also a challenge for more open systems
 * can point to places where decentralized still wins - there's open source centralization, e.g. rendering engines (Chromium is open source/Blink); same with Apache and most of the cloud infra powered by open source software
