= Reframing Competition
:bibliography-database: foc_bibliography.bib
:bibliography-style: apa

This is a short (1500 words) piece on the problem with framing big
tech problems as competition/antitrust.

News hook? House Judiciary Committee will introduce legislation.  Timing unknown.
Current status of House Jud process as of March: A series (~10) of small bills will be introduced in May to cover different aspects of competition reform. That could set us up to write a piece that categorizes their interventions into "things that are part of traditional antitrust" and, if any "things that are unique to the internet" (most notably an interoperability mandate, which I expect will be included).

== Introduction

Big tech is begging for regulation.  A few large platforms dominate
online communication.  Everybody has a list of complaints.  They sell
our privacy, restrict the wrong speech, and encourage discord.  People
want to leave these services, but they're the only way to keep up with
friends and family.  Many of us feel trapped in a relationship with
services that are clearly not doing their best to care for us as
dependent users.

This feels like a problem of bigness.  Too few, too large players have
so much power they can make decisions that prioritize their profits
instead of our relationships.  In looking for solutions, naturally, we
reach for the tools that have helped us deal with companies that have
grow too big and amassed too much power. We look to laws and
regulations that govern monopolies, trusts, and competition.

These old, loved tools are maybe not the best, the most modern we
might have, but they work and we know how to use them.  They need
sharpening.  Some no long work as designed.  In a few cases, we lost
crucial parts and safety equipment along the way.  Most of all,
though, some of these old tools need replacement.  That's what this
piece is about.  Here we argue that our old frameworks for addressing
the problems of bigness in aluminum markets and telephone wires no
longer match up with the harms of today's giant companies and the
concentration of power in communications.

Competition is about the power of market participants.  We take for
granted that rules concerning the balance of power between competitors
will trickle down to benefit consumers by shifting the power
balance toward customers.  But there is a lot of distance between
those rules and the consumers regulations are supposed to help.  If
what we want is to empower users and give them meaningful choices,
perhaps there are ways we can do that more directly.

 * The frame isn't wrong when you apply it to the things it is good at, it's good.
 * To stretch that or to fail to contextualize that properly is to miss the core of the internet.
 * We should make the point that what matters in this space is power, not competition and yet competition IS about power

== Argument

=== Neither competition nor communications paradigms describe the internet perfectly

The internet is something new, and yet we continue to examine it through old frames of reference. We see large, successful businesses whose actions are perceived by smaller competitors to limit market entry and fair competition, so we look to apply antitrust; yet that doesn't tell the full story, and our toolkit may well not have the right metrics or remedies to evaluate and redress the underlying harms. At the other end of the spectrum, we have a history of accepting the market positions of incumbents who offer communications services, and mitigating the potential for harm through specific structural and behavioral obligations, derived from even older common carriage principles. But that, too, is imperfect in many ways when considered for extension to the internet, for example through the frame of "stack neutrality". cite:[wexthayer01]
Structural differences won't stop advocates for reform from trying to apply existing doctrines to new contexts. Reform efforts have heated up with antitrust in particular, with multiple lawsuits filed against Google and Facebook (separately) asserting monopoly status and illegal anti-competitive practices. It will take years for these matters to reach trial, and it's not hard for a wealthy defendant to argue over market definition and power until the clock runs out on an administration or a session of Congress; political winds shift much quicker and more fluidly than court schedules.
These are complex and challenging questions, grounded in very real harms resulting from the actions of companies that have, at the same time, done incredibly positive things as well. But we will be limited in our ability to get that balance right so long as we continue approaching them principally through flawed metaphors that fail to recognize the unique technical characteristics of the internet (consider cite to https://www.internetsociety.org/internet-invariants-what-really-matters/).
(I think we can focus it by simply pivoting to the idea that we don't need to reject these frames and all of these discussions have their place - but we need to supplement them with net-native paradigms and theories of governance.)

=== Ways current frameworks don't describe reality
 * Antitrust / common carrier spectrum, this is new
 * It takes so long to argue the current market power / competition framework that companies get to wait out the clock on administrations
 * Common carrier is another frame people reach for but there's no good reason for it here.
 * recognize the limits of our framing, and the thing that we craft now has to bridge the gap in our conceptual reality
 * Options != competition necessarily - just because I'm making an alternative client doesn't mean I'm competing with you.  It affects power and not competition.

=== Ways current framework solutions don't match the need/reality
 * structural separation is looking at structures the wrong way - metaphor of industrial supply chain integration is wrong. consider what it looks like to re-imagine an integrated user-facing service as a composite of both an infrastructure and a retail function. after all, that's how it's engineered in practice - and why there are separate engineering teams for each function, and private APIs powering their intersection. what does it look like to re-imagine the conversation we're having around structural separation, which is too often grounded in historical yet inapposite theories of the undoing of mergers (whether stylized as vertical or horizontal), in that lens?
 * even governance paradigms need new thinking - we are swinging on a pendulum between hands-off self-governance first and towards regulatory intervention that specifies specific practices or outcomes. that isn't the net-native approach, which is one that promotes responsible, transparent, adaptive innovation and growth. what does effective co-regulatory governance look like that creates incentives for tech to be developed for good and with accountability (because we know now those things don't just happen on their own), but without paternalism and undue ex ante restriction?

== Conclusions
=== We get why the current frameworks get used

In the short term, it is easiest and most productive to reach for
existing frameworks.  Anybody seeking to change current behavior
naturally reaches for current tools.  Enacting new frameworks for
regulating online activity is a long and fraught process.

=== We need different frames

=== Better solutions will come from better metaphors
 * We need something streamlined to prevent waiting out the clock

Future of Openness
[insert some more setup here about competition context]
 * The magic formula for the internet is open infrastructure --> level playing field for edge, and open and closed all welcome at the edge.
 * The problem today is that we’re at a transition moment where the nature of what is infrastructure is changing.
 * Certain things have become infrastructure in practice, and are not open enough to lead to maximum benefit.
 * Those things could include search, social, platform access (incl Amazon virtual storefront and Apple/Google Play app stores). Which is not to determine that any of those things are truly considered infrastructure, but rather as a way of reframing the nature of the gatekeeper behavior that is demonstrable qualitatively if not yet (or ever?) quantitatively
 * The gatekeeper behavior we’re talking about can, sort of, be cast in light of traditional economic concepts like market entry and user switching costs. But a better articulation/formulation is as a gatekeeper of downstream innovation.
 * From the perspective of protecting the future of openness by limiting gatekeeper control over downstream innovation, the structural remedy conversation is a bit off. We shouldn’t be focused on whether Amazon and AWS are owned by the same company, or even FB and Instagram. We should focus on understanding the difference between the infrastructure-like component and the retail user experience component. (Could cite e.g. Twitter and the vision of a range of user experiences for how to present and order - that reflects the distinction.)


== Notes from our discussion
  * Zero marginal cost of goods is not part of our argument.
  * when power hits coercive levels, we have problems
 * Coercion is a spectrum and some coercion might be ok
 * Omnipresence can create this coercion, not just monopoly
 * One antidote to this is options (or competition or agency)

 * Policy framed around monopoly isn't useful-- use can have coercion without monopoly, and the solutions aren't centered on competition.  We're also not worried about consumer pricing
 * The availability of options is important even if you never take them (think forking open source code, or building new apps and services)
 * The traditional language, framing, and legal concepts around antitrust don't fit this. There are practical reasons to need to squeeze the internet circle into these squares to use existing law in litigation; but for new regulatory approaches, we can and should recognize the nature of this and approach it more effectively.
 * Maybe we can ask some EU folks for the framing over there so we can either take good ideas or cite them as more examples of poor framing
 * If competition is the wrong frame, maybe "Future Of Competition" is the wrong title
 * We need more work here to develop the *right* frame
 * Feld also critiques the "resort to antitrust", and he (as is typical) tosses in some history on regulation for the public good as opposed to for market management. cite:[feld01, locator="Introduction, Section A"]
 * interoperability is gaining traction, along with structural separation
 * one idea: we're framing this wrong - the harm we're tracking isn't antitrust harm per se, or consumer harm, it's user harm - the point is not "hey stop framing it this way" but rather "recognize that where we're coming from shapes our current state" - we can and must work with the structures that we have, but it's critical to acknowledge the flaws in the metaphor
 * need to allude to places where the framing leads us astray but without going too far down the rabbit holes
 * grounded in US law/policy and regulatory philosophy but this is a broader conversation particularly in EU+UK
 * we're looking to a future where different regions experiment with applying different regulatory+enforcement paradigms to this still-new space - UK w OFCOM implementing the duty of care, EU with multi-state mechanisms (like DPAs) - lots of things will break over the next few years, and that's OK as long as we learn from it and iterate with our governance in the same way we iterate with our technology
 * infrastructure works best when it's open. search, social, etc are now infra in a way they haven't been before. we expect more openness now than we did, and we should expect that because it's the optimal approach. just because the infra is vertically integrated with the UX doesn't mean it isn't infra.
 * If you're going to break anything up, the answer isn't to force Google to dump YouTube, it's separating the platform infra from the UI, which can effectively be done via interop. Same for Facebook - you don't carve out Instagram, you separate the network infra core from the UI. Google search does have at least some interop in this sense.  See https://startpage.com/.  Google apparently shares the index, but not the click data that helps them score it.  Where do we draw the line between the platform and the UI.  Is the click trail part of the platform?  We would say definitely. Why though and what are the repeatable principles that help extend it?

=== Counterpoint: we're framing this right
 * There are some aspects of regulating big tech that *are* rightly about competition
 * exclusivity agreements, acquisition of threats, non-compete, no-poaching agreements, etc.
 * We need to acknowledge that talk about the dividing line
 * We need to deal with this complexity in the regulatory approach to some degree
