= Reframing Competition
:bibliography-database: foc_bibliography.bib
:bibliography-style: apa

This is a short (1500 words) piece on the problem with framing big
tech problems as competition/antitrust.

News hook? House Judiciary Committee will introduce legislation.  Timing unknown.

== Introduction
 * Competition is about power of participants
 * The frame isn't wrong when you apply it to the things it is good at, it's good.
 * To stretch that or to fail to contextualize that properly is to miss the core of the internet.

== Argument

=== Neither competition nor communications paradigms describe the internet perfectly
The internet is something new, and yet we continue to examine it through old frames of reference. We see large, successful businesses whose actions are seen as limiting market entry and fair competition, so we look to apply antitrust; yet that doesn't tell the full story, and our toolkit doesn't seem to have the right metrics or remedies. At the other end of the spectrum, we have a history of accepting the market positions of incumbents who offer communications services, and mitigating the potential for harm through specific structural and behavioral obligations, derived from even older common carriage principles. But that, too, is imperfect in many ways.
It won't stop advocates for reform from trying, naturally. And things have heated up with antitrust in particular, with multiple lawsuits filed against Google and Facebook (separately) asserting monopoly status and illegal anti-competitive practices. It will take years for these matters to reach trial, and Congress has shown no signs of waiting, as both the House and Senate prepare to take up legislation to increase competition restrictions on tech companies (add cites). It's not hard for a wealthy defendant to argue over market definition and power until the clock runs out on an administration or a session of Congress; political winds shift much quicker and more fluidly than court schedules.
Meanwhile, Congress and the general public are re-examining the tradeoffs built into the infamous immunity provision of Section 230 of the Communications Act, with several bills introduced that propose repeal or massive reform. Unlike with antitrust, there's no plausible enforcement action or other remedy absent statutory change--although that didn't stop the Trump administration from trying a long-shot executive order directing the NTIA to press FCC on the matter (add cite to https://trumpwhitehouse.archives.gov/presidential-actions/executive-order-preventing-online-censorship/ ).
These are complex and challenging questions, grounded in very real harms resulting from the actions of companies that have simultaneously done incredible things. But we continue approaching them through flawed metaphors that fail to recognize the unique technical characteristics of the internet (consider cite to https://www.internetsociety.org/internet-invariants-what-really-matters/).
(Is this framing too big? I feel a bit like we're trying to tackle everything, and really we could consider focusing specifically on structural separation as that concept is used - there's a narrower piece to write here about structural separation vs essential facilities doctrine vs common carrier obligations vs interoperability that could be an illustration of the broader point, without necessitating such ambitious rhetoric at the top.)
(We could then make this a more practical piece that says - the internet is changing, it's always changing, to support that change the current discussions around structural separation are at risk of missing the mark - just as the ones about "stack neutrality" or other attempts to import common carrier principles from communications law directly are off the mark. the idea of a "Gatekeeper" could be useful if separated from the narrower economic/antitrust contexts, perhaps...)
=== Ways current framework solutions don't match the need/reality
 * structural separation is looking at structures the wrong way
== Conclusion
=== We get why the current frameworks get used
=== We need different frames
=== Better solutions will come from better metaphors
 * We need something streamlined to prevent waiting out the clock

Future of Openness
[insert some more setup here about competition context]
 * The magic formula for the internet is open infrastructure --> level playing field for edge, and open and closed all welcome at the edge.
 * The problem today is that we’re at a transition moment where the nature of what is infrastructure is changing.
 * Certain things have become infrastructure in practice, and are not open enough to lead to maximum benefit.
 * Those things could include search, social, platform access (incl Amazon virtual storefront and Apple/Google Play app stores). Which is not to determine that any of those things are truly considered infrastructure, but rather as a way of reframing the nature of the gatekeeper behavior that is demonstrable qualitatively if not yet (or ever?) quantitatively
 * The gatekeeper behavior we’re talking about can, sort of, be cast in light of traditional economic concepts like market entry and user switching costs. But a better articulation/formulation is as a gatekeeper of downstream innovation.
 * From the perspective of protecting the future of openness by limiting gatekeeper control over downstream innovation, the structural remedy conversation is a bit off. We shouldn’t be focused on whether Amazon and AWS are owned by the same company, or even FB and Instagram. We should focus on understanding the difference between the infrastructure-like component and the retail user experience component. (Could cite e.g. Twitter and the vision of a range of user experiences for how to present and order - that reflets the distinction.)


== Notes from our discussion
  * Zero marginal cost of goods is not part of our argument.
  * when power hits coercive levels, we have problems
 * Coercion is a spectrum and some coercion might be ok
 * Omnipresence can create this coercion, not just monopoly
 * One antidote to this is options (or competition or agency)
 * Options != competition necessarily
 * Policy framed around monopoly isn't useful-- use can have coercion without monopoly, and the solutions aren't centered on competition.  We're also not worried about consumer pricing
 * Common carrier is another frame people reach for but there's no good reason for it here.
 * The availability of options is important even if you never take them (think forking open source code, or building new apps and services)
 * The traditional language, framing, and legal concepts around antitrust don't fit this. There are practical reasons to need to squeeze the internet circle into these squares to use existing law in litigation; but for new regulatory approaches, we can and should recognize the nature of this and approach it more effectively.
 * Maybe we can ask some EU folks for the framing over there so we can either take good ideas or cite them as more examples of poor framing
 * If competition is the wrong frame, maybe "Future Of Competition" is the wrong title
 * We need more work here to develop the *right* frame
 * Feld also critiques the "resort to antitrust", and he (as is typical) tosses in some history on regulation for the public good as opposed to for market management. cite:[feld01, locator="Introduction, Section A"]
 * interoperability is gaining traction, along with structural separation
 * one idea: we're framing this wrong - the harm we're tracking isn't antitrust harm per se, or consumer harm, it's user harm - the point is not "hey stop framing it this way" but rather "recognize that where we're coming from shapes our current state" - we can and must work with the structures that we have, but it's critical to acknowledge the flaws in the metaphor
 * recognize the limits of our framing, and the thing that we craft now has to bridge the gap in our conceptual reality
 * need to allude to places where the framing leads us astray but without going too far down the rabbit holes
 * grounded in US law/policy and regulatory philosophy but this is a broader conversation particularly in EU+UK
 * we're looking to a future where different regions experiment with applying different regulatory+enforcement paradigms to this still-new space - UK w OFCOM implementing the duty of care, EU with multi-state mechanisms (like DPAs) - lots of things will break over the next few years, and that's OK as long as we learn from it and iterate with our governance in the same way we iterate with our technology
 * infrastructure works best when it's open. search, social, etc are now infra in a way they haven't been before. we expect more openness now than we did, and we should expect that because it's the optimal approach. just because the infra is vertically integrated with the UX doesn't mean it isn't infra.
 * If you're going to break anything up, the answer isn't to force Google to dump YouTube, it's separating the platform infra from the UI, which can effectively be done via interop. Same for Facebook - you don't carve out Instagram, you separate the network infra core from the UI. Google search does have at least some interop in this sense.  See https://startpage.com/.  Google apparently shares the index, but not the click data that helps them score it.  Where do we draw the line between the platform and the UI.  Is the click trail part of the platform?  We would say definitely. Why though and what are the repeatable principles that help extend it?

=== Counterpoint: we're framing this right
 * There are some aspects of regulating big tech that *are* rightly about competition
 * exclusivity agreements, acquisition of threats, non-compete, no-poaching agreements, etc.
 * We need to acknowledge that talk about the dividing line
 * We need to deal with this complexity in the regulatory approach to some degree
