= Reframing Competition
:bibliography-database: foc_bibliography.bib
:bibliography-style: apa

This is a short (1500 words) piece on the problem with framing big
tech problems as competition/antitrust.

News hook? House Judiciary Committee will introduce legislation.  Timing unknown.

== Introduction
 * Competition is about power of participants
 * The frame isn't wrong when you apply it to the things it is good at, it's good.
 * To stretch that or to fail to contextualize that properly is to miss the core of the internet.
== Argument
=== Ways current frameworks don't describe reality
 * Antitrust / common carrier spectrum, this is new
 * It takes so long to argue the current market power / competition framework that companies get to wait out the clock on administrations
=== Ways current framework solutions don't match the need/reality
== Conclusion
=== We get why the current frameworks get used
=== We need different frames
=== Better solutions will come from better metaphors
 * We need something streamlined to prevent waiting out the clock

Future of Openness
[insert some more setup here about competition context]
 * The magic formula for the internet is open infrastructure --> level playing field for edge, and open and closed all welcome at the edge.
 * The problem today is that we’re at a transition moment where the nature of what is infrastructure is changing.
 * Certain things have become infrastructure in practice, and are not open enough to lead to maximum benefit.
 * Those things could include search, social, platform access (incl Amazon virtual storefront and Apple/Google Play app stores). Which is not to determine that any of those things are truly considered infrastructure, but rather as a way of reframing the nature of the gatekeeper behavior that is demonstrable qualitatively if not yet (or ever?) quantitatively
 * The gatekeeper behavior we’re talking about can, sort of, be cast in light of traditional economic concepts like market entry and user switching costs. But a better articulation/formulation is as a gatekeeper of downstream innovation.
 * From the perspective of protecting the future of openness by limiting gatekeeper control over downstream innovation, the structural remedy conversation is a bit off. We shouldn’t be focused on whether Amazon and AWS are owned by the same company, or even FB and Instagram. We should focus on understanding the difference between the infrastructure-like component and the retail user experience component. (Could cite e.g. Twitter and the vision of a range of user experiences for how to present and order - that reflets the distinction.)


== Notes from our discussion
  * Zero marginal cost of goods is not part of our argument.
  * when power hits coercive levels, we have problems
 * Coercion is a spectrum and some coercion might be ok
 * Omnipresence can create this coercion, not just monopoly
 * One antidote to this is options (or competition or agency)
 * Options != competition necessarily
 * Policy framed around monopoly isn't useful-- use can have coercion without monopoly, and the solutions aren't centered on competition.  We're also not worried about consumer pricing
 * Common carrier is another frame people reach for but there's no good reason for it here.
 * The availability of options is important even if you never take them (think forking open source code, or building new apps and services)
 * The traditional language, framing, and legal concepts around antitrust don't fit this. There are practical reasons to need to squeeze the internet circle into these squares to use existing law in litigation; but for new regulatory approaches, we can and should recognize the nature of this and approach it more effectively.
 * Maybe we can ask some EU folks for the framing over there so we can either take good ideas or cite them as more examples of poor framing
 * If competition is the wrong frame, maybe "Future Of Competition" is the wrong title
 * We need more work here to develop the *right* frame
 * Feld also critiques the "resort to antitrust", and he (as is typical) tosses in some history on regulation for the public good as opposed to for market management. cite:[feld01, locator="Introduction, Section A"]
 * interoperability is gaining traction, along with structural separation
 * one idea: we're framing this wrong - the harm we're tracking isn't antitrust harm per se, or consumer harm, it's user harm - the point is not "hey stop framing it this way" but rather "recognize that where we're coming from shapes our current state" - we can and must work with the structures that we have, but it's critical to acknowledge the flaws in the metaphor
 * recognize the limits of our framing, and the thing that we craft now has to bridge the gap in our conceptual reality
 * need to allude to places where the framing leads us astray but without going too far down the rabbit holes
 * grounded in US law/policy and regulatory philosophy but this is a broader conversation particularly in EU+UK
 * we're looking to a future where different regions experiment with applying different regulatory+enforcement paradigms to this still-new space - UK w OFCOM implementing the duty of care, EU with multi-state mechanisms (like DPAs) - lots of things will break over the next few years, and that's OK as long as we learn from it and iterate with our governance in the same way we iterate with our technology
 * infrastructure works best when it's open. search, social, etc are now infra in a way they haven't been before. we expect more openness now than we did, and we should expect that because it's the optimal approach. just because the infra is vertically integrated with the UX doesn't mean it isn't infra.
 * If you're going to break anything up, the answer isn't to force Google to dump YouTube, it's separating the platform infra from the UI, which can effectively be done via interop. Same for Facebook - you don't carve out Instagram, you separate the network infra core from the UI. Google search does have at least some interop in this sense.  See https://startpage.com/.  Google apparently shares the index, but not the click data that helps them score it.  Where do we draw the line between the platform and the UI.  Is the click trail part of the platform?  We would say definitely. Why though and what are the repeatable principles that help extend it?

=== Counterpoint: we're framing this right
 * There are some aspects of regulating big tech that *are* rightly about competition
 * exclusivity agreements, acquisition of threats, non-compete, no-poaching agreements, etc.
 * We need to acknowledge that talk about the dividing line
 * We need to deal with this complexity in the regulatory approach to some degree
